version: '3.7'

x-base: &base
  volumes:
    - "$HOME/.aws:/root/.aws"
    - "$HOME/.kube:/root/.kube"
    - ".:/app"
  working_dir: /app
  ports:
    - "5000:5000"

services:

  sh:
    <<: *base
    build:
      context: .
      target: release
    entrypoint: bash

  server:
    <<: *base
    build:
      context: .
      target: release
    entrypoint:
      - gunicorn
      - -c
      - src/gunicorn.conf.py
      - src.server:app

  release:
    <<: *base
    build:
      context: .
      target: release
    image: ikerry/kube-py-app:${APP_IMAGE_TAG:-latest}
